export { default as BubbleSort } from "./BubbleSort";
export { default as Home } from "./Home";
export { default as MergeSort } from "./MergeSort";
export { default as QuickSort } from "./QuickSort";
export { default as SelectionSort } from "./SelectionSort";
export { default as Tutorial } from "./Tutorial";
export { default as Datenschutz } from "./Datenschutz";
export { default as Impressum } from "./Impressum";
export { default as Kontakt } from "./Kontakt";
