# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm" # See documentation for possible values
    # Look for `package.json` and `package-lock.json` files
    directories:
      - "/"
      - "/frontend"
      - "/backend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Group pull requests together
    groups:
      npm-dev-deps:
        dependency-type: "development"
      npm-prod-deps:
        dependency-type: "production"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    groups:
      docker-deps:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
