# For Development

services:
  frontend:
    build:
      target: frontend
    container_name: frontend
    ports:
      - "8080:80"

  backend:
    build:
      target: backend
    container_name: backend
