# How many parallel processes to handle client requests
worker_processes auto;

events {
    # Per worker process: how many simultaneous connections can be opened
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types; # To let Nginx handle file types like .js and .css
    default_type application/octet-stream; # Prevents nginx from defaulting to test/plain

    # HTTP
    server {
        listen 80;
        listen [::]:80;
        server_name audojo.org www.audojo.org;
        server_tokens off;

        # Redirect HTTP to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name audojo.org www.audojo.org;
        server_tokens off;

        # SSL certificates
        ssl_certificate /etc/ssl/cloudflare/audojo.pem;
        ssl_certificate_key /etc/ssl/cloudflare/audojo.key;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
