name: Build Project

# Trigger workflow on push or pull request to every branch
on:
  push:
    paths-ignore:
      - "**/*.md"
  # pull_request:

# Workflow jobs
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache npm and .eslintcache
      - name: Cache npm cache and .eslintcache
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/.eslintcache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm ci --ignore-scripts --prefix backend
          npm ci --ignore-scripts --prefix frontend
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
