name: Build Project

# Trigger workflow on push or pull request to every branch
on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"
  # pull_request:

# Workflow jobs
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Cache npm and .eslintcache
      - name: Cache .eslintcache
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            **/.eslintcache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
