name: Lint Commit Messages
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [synchronize, opened, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    if: |
      github.event_name == 'push' ||
      (github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
