name: Playwright Tests
on:
  push:
    branches: [main, dev, production]
  pull_request:
    branches: [main, dev, production]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble # Keep version in sync with package.json
      options: --user 1001
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Playwright tests
        run: pnpm playwright test --project=chromium

      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: blob-report
          path: blob-report/
          retention-days: 7
#TODO: When more tests are added, activate this parallel workflow
# name: Playwright Tests
# on:
#   push:
#     branches: [main, dev, production]
#   pull_request:
#     branches: [main, dev, production]
# jobs:
#   playwright-tests:
#     name: "Test (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})"
#     strategy:
#       fail-fast: false # CI won't stop other jobs if one fails
#       matrix:
#         # project: [chromium, firefox, webkit]
#         shardIndex: [1, 2, 3, 4]
#         shardTotal: [4]
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright:v1.50.1-noble # Keep version in sync with package.json
#       options: --user 1001
#     steps:
#       - uses: actions/checkout@v5
#       - uses: pnpm/action-setup@v4
#       - uses: actions/setup-node@v6
#         with:
#           node-version: lts/*
#           cache: pnpm

#       - name: Install dependencies
#         run: pnpm install --frozen-lockfile

#       - name: Run Playwright tests
#         run: pnpm playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

#       - name: Upload blob report to GitHub Actions Artifacts
#         uses: actions/upload-artifact@v5
#         if: ${{ !cancelled() }}
#         with:
#           name: blob-report-${{ matrix.shardIndex }}
#           path: blob-report/
#           retention-days: 1

#   merge-reports:
#     # Merge reports after playwright-tests, even if some shards have failed
#     if: ${{ !cancelled() }}
#     needs: [playwright-tests]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: pnpm/action-setup@v4
#       - uses: actions/setup-node@v6
#         with:
#           node-version: lts/*
#           cache: pnpm

#       - name: Install dependencies
#         run: pnpm install --frozen-lockfile

#       - name: Download blob reports from Github Actions Artifacts
#         uses: actions/download-artifact@v4
#         with:
#           path: all-blob-reports
#           pattern: blob-report-*
#           merge-multiple: true

#       - name: Merge into HTML Report
#         run: pnpm playwright merge-reports --reporter html ./all-blob-reports

#       - name: Upload HTML report
#         uses: actions/upload-artifact@v5
#         with:
#           name: html-report--attempt-${{ github.run_attempt }}
#           path: playwright-report
#           retention-days: 14
